### ISSUE TITLE
self-study quiz needs improvement

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#108]
A few more things need to be styled, e.g.:

![ssquiz-missing](https://user-images.githubusercontent.com/653208/218857532-6edd71e2-b254-4ae5-86a1-ae6ca16239c8.jpg)

**Comment by Sepitus-exe** [comment]
Was this issue solved with the changes included in PR #111, or is there something more that needs to be done?

**Comment by wrex** [comment]
Yes, this was fixed in #111 -- closing
