### ISSUE TITLE
Lesson kana charts are missing styling

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#110]
![image](https://user-images.githubusercontent.com/82216846/220209007-54f47662-aa8e-42ff-92dd-946cd13ea030.png)

**Comment by wrex** [comment]
I don't have any lessons any more, so I'd have to create a new account to test.

I'll assign to you instead. :-)

**Comment by wrex** [comment]
Also, what in the heck: あ　か　さ　た　**は**　な　。。。

The normal 五十音 order is あかさたなはまやらわん!!
