### ISSUE TITLE
Darken meaning reviews (?)

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#19]
This is a judgement call, but ~~review pages are significantaly brighter with  vocabulary items than with kanji items~~. [EDIT: Nope, the green is lighter, but it's _meaning_ reviews that get the white input bar.]

The input background for ~~kanji items~~ [Readings] is dark (with light text), for ~~vocab~~ [Meanings] it's white (with dark text). Coupled with the fairly light green, it makes for a noticeably "bright" screen for a dark theme.

I think just using light text on a dark background will suffice, but personally, I'll likely darken the green a bit (everywhere, not just here).

The issue is exacerbated by the enormous div at the top of the screen. The green color would be fine in small quantities, but it's  painfully bright when it take sup half the screen.

-- 

Whoops. Just realized this isn't a kanji/vocab thing, it's a meaning/reading thing. It's the meaning pages that are too bright with a white input bar.

**Comment by Sepitus-exe** [comment]
The white backgrounds were initially kept true to the original theme to help with distinguishing reading and meaning prompts. But I must concur, they are way too bright. I would probably move to a light shade of gray or at least a lighter shade than what the reading header uses to keep this feature in.

When it comes to green and even yellow. I'm currently conflicted. There are places where they work and places where they don't. My main issue isn't the brightness, but how faded white text on them is. I'm probably going to split them into multiple shades and decide from case to case where to use which. Let's be real, getting a correct answer to a vocabulary question doesn't look very good atm. Feel free to change the colors however you see fit.

**Comment by wrex** [comment]
Oh, I definitely agree that some sort of visual prompt is definitely necessary to distinguish reading questions from meaning questions. Even the default behavior from WK is too subtle, IMO (I was on level 17 before I even noticed!).

But dark themes can't just invert colors, they need to define new ones. As you point out, just backing off from #fff will help a ton.

Re: green/yellow, there are plenty of usability checkers available that will validate the contrast. As long as those checks pass anything goes. I don't think you can just keep pure white text on everything though, unfortunately. `background-color` and `color` need to coordinate with each other.

Let me tinker a bit.

**Comment by wrex** [comment]
I think the current colors work. Close?
