### ISSUE TITLE
Reduce box-shadow on stage change notifications

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#20]
Just a minor nit. The box shadow is pretty egregious when you finish both halves of a review and get the notification about it's new stage:

<img width="630" alt="Screenshot 2023-01-14 at 1 42 43 PM" src="https://user-images.githubusercontent.com/653208/212499981-3d4d8221-5ad5-4cd5-8ed7-0cda56954aed.png">

It's particularly bad with red on green as shown (apprentice stage on a vocabulary item).

Here's the relevant markup:

<img width="549" alt="Screenshot 2023-01-14 at 1 43 24 PM" src="https://user-images.githubusercontent.com/653208/212500011-7b561f9b-21ac-42c0-9ee4-bcca6ba477a5.png">

## Separate concern

I'll let you decide if you want to make this change, but personally, I think that it's best if themes **don't** change the default hue or saturation of things that mean SRS stages. It's okay to mess with the lightness, but I think you should leave the hue and saturation alone.

For reference:

- Apprentice: pink, hsl(320deg 100% 43%) 
- Guru: purple, hsl(288deg 56% 40%)
- Master: blue, hsl(228deg 71% 51%)
- Enlightened: light-blue, hsl(200deg 100% 43%)

I think keeping these hues the same causes less mental friction for users. 

Changing the hues for things with semantic meanings of "radical", "kanji", or "vocabulary" is less of an issue, IMO, because users spend most of their review time bouncing between kanji and vocab -- they quickly learn the meaning of new colors (just two things to remember, radicals become the odd-man-out on occasion). 

With four stages though, and hundreds of items constantly moving up and down, it becomes confusing if a theme changes the hue of things that semantically mean apprentice/guru/master/enlightened.

**Comment by Sepitus-exe** [comment]
The text-shadow is going away for sure. It was a makeshift solution to make red text readable on a red background. But since I plan to introduce more shades of red, blue, green, and yellow, it will become obsolete.

---

Keeping the original SRS stage colors? I don't know about that one. I get the reasoning behind it, but I feel like the colors would clash way too much with the current palette. There is a debate about usability vs appearance to be had. For now, I'm primarily going to focus on the current colors and check the official ones out at a later date.

**Comment by wrex** [comment]
I note that the default colors have a different `background-color` for the text:

<img width="527" alt="Screenshot 2023-01-14 at 1 44 34 PM" src="https://user-images.githubusercontent.com/653208/212501559-64347bc2-c44a-456c-8538-bf3064623a4c.png">

For the elementary dark theme, you could set the `background-color` to pure white, then use `backdrop-filter` that will work with any foreground `color` you like. A'la: https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter

**Comment by Sepitus-exe** [comment]
Ngl, I forgot there was a box with its own background-color there. I made it transparent when I was experimenting with a plain white message. It never occur to me I could just add it back. Also I never heard of backdrop-filters, but they look awesome. I'm sure they would make an excellent addition.

**Comment by wrex** [comment]
Post Issue #23, there is a background again for all of these. Currently uses the default text color for stuff progressing (`.srs-up`) and grayed text for stuff falling back (`.srs-down`).

Closing.
