### ISSUE TITLE
Empty kotoba boxes

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#29]
![img](https://user-images.githubusercontent.com/82216846/212811630-fa442a20-012b-4706-a2df-c6f7c488c07b.png)

**Comment by wrex** [comment]
I ended up with no critical items and only 10 reviews this morning, so I was able to take this one.

**Comment by Sepitus-exe** [comment]
Thanks worked like a charm. If you are still interested in removing the "see more" button from empty tables, I left a sort of solution in the merge request comments.
