### ISSUE TITLE
Bleeding kanji styling - Pending confirmation

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#30]
![img](https://user-images.githubusercontent.com/82216846/212812874-22f58e37-2a29-4c27-9d2a-64341910c642.png)

**Comment by wrex** [comment]
Can confirm this is fixed:
<img width="1264" alt="Screenshot 2023-01-17 at 5 00 27 PM" src="https://user-images.githubusercontent.com/653208/213055063-0b369f66-4b02-44c0-b446-acbe7a080bda.png">

Note the button bar looks better. The kana height is fixed, and the audio button is close (bugging me tracking down the last few pixels, but we've got bigger fish to fry).

**Comment by Sepitus-exe** [comment]
Awesome, the button hights were bugging me as well. So much so, that there is a seperate issue #9 dedicated to this exact thing. I will close be closing that too.
