### ISSUE TITLE
Distorted Lesson Quiz heders - Pending confirmation

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#32]
![image](https://user-images.githubusercontent.com/82216846/213054609-395fe24c-6f6c-4c50-81db-a3ac51b04d2a.png)

**Comment by wrex** [comment]
I think this is fixed in main. Please verify and close if so.

**Comment by Sepitus-exe** [comment]
Can confirm. Looks like it was fixed with the first mayor wave of post merger cleanups
