### ISSUE TITLE
Heder L/R buttons :active style

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#33]
:hover works fine, but :focus and :active still use default formating

![image](https://user-images.githubusercontent.com/82216846/213057426-d942a5f2-d3b1-4fcb-8e44-39a21729f0a1.png)

might be limited in scope to pages outside dash

**Comment by wrex** [comment]
I always get accessibility stuff wrong.

I think we want the same styling on :hover and :focus, but isn't :active something different?

Anyway, I'm making the default outline around the navigation shortcuts a bit lighter (surface-4) by default, then going to text-color on hover and focus. I'm unsure whether I should or shouldn't do this as well for `:active`.

I also noted that the hover/focus outlines for the "level," "help", and "search" (magnifying-glass icon) are also too subtle. I'll try to change them to text-color on hover/focus as well.
