### ISSUE TITLE
Style WKOF menus

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#56]
I'm losing my mind. I'd have sworn I already added an issue and started working on this, but now I can't find it.

Anyway, WKOF itself pops up some menus when it's loading stuff from the API, to let users change script settings, etc.

Current styling is unusable if ED is loaded: 

<img width="644" alt="Screenshot 2023-01-27 at 7 38 29 PM" src="https://user-images.githubusercontent.com/653208/215240384-d34d672a-8c6d-4424-b274-aa506157b811.png">

**Comment by Sepitus-exe** [comment]
It looks like there is an unmerged branch `40-style-wkof-menus`. I will create a PR for it as well as review it, while Im at it.
