### ISSUE TITLE
WKED-wkof-menus.css should be absorbed into the main file

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#61]

**Comment by wrex** [comment]
I need to do some cleanup, first. I noticed that some of the text isn't getting colored correctly in the popup while loading review data. I think I can just set color and background-color on a few top-level classes and rely on inheritance.

Let me work on this a bit. May take a while to test thoroughly. Caching makes it tricky (and I have a LOT of review records cached -- I'd rather wait another day to test again than keep blowing away my cache).

**Comment by wrex** [comment]
Note that I merged this into the "README" branch for Pull Request #65 as well (I wanted a branch with everything to test).
