### ISSUE TITLE
Is extra-clr needed?

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#62]
Wanted to capture this before I fade for the night.

We have colors for radical/kanji/vocab and "extra".

But as far as I can tell "extra" is mostly the little indicators below each item in the level progress table.

I'm setting extra-clr to be the same as brand in my stylesheet. Seems like it could be set to either progress-clr or brand, but is it worthy of it's own prop?

**Comment by Sepitus-exe** [comment]
If I recall correctly, it was used primarily as an enlightened color with some minor uses like the aforementioned progress indicators. Both of these were deligated to other semantic variables, so Im all for removing it.

**Comment by wrex** [comment]
Removed in the 34-update-readme branch.
