### ISSUE TITLE
Should we rename text-light?

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#76]
Since it's possible to create light color schemes with these props, it occurs to me that we should probably rename a few props. "Light" and "Dark" become confusing.

Proposal:

- Change `--ED-text-light` to `--ED-text-color` (remembering we already have `--EDI-text-color` that gets redefined in the rules)

- Change `--ED-text-dark` to `--ED-inverted-text`

- Change `--ED-light-surface-5` to `--ED-inverted-surface`

Thoughts?

**Comment by Sepitus-exe** [comment]
Probably a wise move.

The light-dark distinction proved functional within the context of the dark theme, but since that vision has shifted to a full-blown framework, we should avoid assumptions of the brightness distribution.
