### ISSUE TITLE
User variables for images

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#97]
~~This might prove to be a tad bit too complex to solve. Never the less,~~ I would like for users to be able to alter the look of some images to fit in better with their overrides.

![image](https://user-images.githubusercontent.com/82216846/218251274-111d7986-9c31-4f74-8cf8-be897c233a1b.png)

---

From my testing, strings without white characters should work here
```
.extra-study img {
  --ED-test: invert(0.81)sepia(1)saturate(5)hue-rotate(80deg);
  filter: var(--ED-test);
}
```
![image](https://user-images.githubusercontent.com/82216846/218251619-31fd9e5f-acab-401b-95be-6284eb5886cc.png)

**Comment by wrex** [comment]
Excellent.

I like that ED is quite straightforward, with no shadows, gradients, or spacing/sizing or other attempts to modify the layout. But recoloring images is kinda mandatory, so this is well worth adding.

**Comment by wrex** [comment]
We want to minimize the number of new custom properties we introduce. It looks like `filter` is used in 20 different places. We may not need to expose some things (like ones that just affect brightness, the kotoba table rows, for example).

I was struggling to decide whether it would be better to name filter variables based on what they _do_ or what they _affect_. Both have pros and cons.

Then I realized the right answer is probably _both_.

We should probably define internal variables based that describe what they _do_, but expose `--ED-*` variables based on what they _affect_ (to make it easier for users to override, but also show them how to do it):

```css
:root {
  --ED-footer-filter: var(--USER-footer-filter, var(--EDI-invert-filter));
  --EDI-invert-filter: invert(100%);

  --ED-copyright-filter: var(--USER-copyright-filter, var(--EDI-pinkish-filter));
  --EDI-pinkish-filter: hue-rotate(50deg)grayscale(0.75)brightness(2.2);

  --ED-locked-item-filter: var(--USER-locked-item-filter, var(--EDI-dim20-filter));
  --EDI-dim20-filter: brightness(80%);

  --ED-kotoba-row-hl-filter: var(--USER-kotoba-row-hl-filter, var(--EDI-bright10-filter));
  --EDI-bright10-filter: brightness(110%);

 ...
}
```

We don't have to expose all of these, of course.

**Comment by Sepitus-exe** [comment]
Approaching it as we do the rest of the variables seems a bit pointless to me. There shouldn't be a reason for a 3rd party to be able to access the exact filter values nor do we need to share them across multiple elements.

I will admit, however that my solution is more on the baren side. It would be beneficial to allow customization beyond just the limited scope I proposed.

**Comment by wrex** [comment]
> There shouldn't be a reason for a 3rd party to be able to access the exact filter values nor do we need to share them across multiple elements.

Oh! Yeah, I agree strongly. I still intended for `--EDI-*` props to be internal only, not for external use.

I just find that using props for filter chains like this let's us document the _intent_ which makes maintenance easier when WK decides to change things (which they will).

I only intended the `--ED-*-filter` props to be overridable in separate stylesheets.
